SOURCES := $(wildcard ./ufo/*.ufo)

OTFS := $(patsubst ./ufo/%.ufo,./autogenerated/otf/%.otf,$(SOURCES))
TTFS := $(patsubst ./ufo/%.ufo,./autogenerated/ttf/%.ttf,$(SOURCES))
WOFFS := $(patsubst ./ufo/%.ufo,./autogenerated/woff/%.woff,$(SOURCES))
WOFF2S := $(patsubst ./ufo/%.ufo,./autogenerated/woff2/%.woff2,$(SOURCES))

all: $(OTFS) $(TTFS) $(WOFFS) $(WOFF2S)

clean:
	rm -rf autogenerated

psfnormalize:
	(cd ufo && sh -c 'for font in *.ufo; do psfnormalize $$font; done')

autogenerated/otf/%.otf: ufo/%.ufo
	@mkdir -p $(@D)
	./process-font.sh $< $@

autogenerated/ttf/%.ttf: ufo/%.ufo
	@mkdir -p $(@D)
	./process-font.sh $< $@

autogenerated/woff/%.woff: ufo/%.ufo
	@mkdir -p $(@D)
	./process-font.sh $< $@

autogenerated/woff2/%.woff2: ufo/%.ufo
	@mkdir -p $(@D)
	./process-font.sh $< $@

fontbakery: all
	fontbakery check-googlefonts --html fontbakery-report.html autogenerated/otf/*.otf
